### ISSUE TITLE
Problem with conversion

### ISSUE THREAD

**Issue by csrednicki** [nomoketo/ttml2srt#8] opened 2018-09-29 13:03 UTC
Hi @codingcatgirl, I have a problem with converting subtitle to srt format. I cloned this repo, installed latest Python 3.7.0 for windows and started it from command line like this:

`python ttml2srt.py "d:\Temp\aaa\S02E12.ttml"`

In return I get:

`Traceback (most recent call last):
  File "ttml2srt.py", line 88, in <module>
    parse_times(body)
  File "ttml2srt.py", line 86, in parse_times
    parse_times(child, default_begin=begin)
  File "ttml2srt.py", line 86, in parse_times
    parse_times(child, default_begin=begin)
  File "ttml2srt.py", line 64, in parse_times
    begin = parse_time_expression(elem.attrib['begin'], default_offset=default_begin)
  File "ttml2srt.py", line 49, in parse_time_expression
    raise NotImplementedError('Parsing time expressions by ticks is not supported!')
NotImplementedError: Parsing time expressions by ticks is not supported!`

I had attached original ttml file. Can you help me?

[S02E12.zip](https://github.com/codingcatgirl/ttml2srt/files/2430646/S02E12.zip)

**Comment by codingcatgirl** [comment] 2018-09-29 16:35
This is a duplicate of #7 and it's exactly what the error message says:"Parsing time expressions by ticks is not supported!"

This TTML file uses "ticks" as a time unit, which is not supported by ttml2srt because it would require information about the video stream.

**Closed as completed by codingcatgirl** 2018-09-29 16:35 UTC

**Comment by codingcatgirl** [comment] 2018-09-29 17:01
My bad, it was a misunderstanding of the specification. ticks are supported now.

**Comment by csrednicki** [comment] 2018-09-29 17:21
Wow, that was quick. Thank you.
